config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout',  to: 'sessions#destroy'
  resources :users, :password_alters, :set_templates, :set_modules, only: [:edit, :update]
  resources :portraits, only: [:new, :create, :update] 
end

app/controllers/password_alters_controller.rb
class PasswordAltersController < ApplicationController
  before_action :logged_in_user

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if !@user.authenticate(params[:password_alter][:old_password])
      @user.errors.add(:old_password, t('incorrect_old_password'))
      render 'edit'
    elsif @user.authenticate(params[:password_alter][:old_password]) && params[:password_alter][:old_password] == params[:password_alter][:password]
      @user.errors.add(:password, "不能使用旧密码进行更新!")
      render 'edit'
    elsif params[:password_alter][:password].empty?
      @user.errors.add(:password, t('can_not_be_blank'))
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = t('password_reset_successfully')
      redirect_to edit_password_alter_path(@user)
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:password_alter).permit(:old_password, :password, :password_confirmation)
    end
end

app/views/password_alters/_password_edit.html.erb
<div class="col-md-10">
  <div class="card">
    <div class="card-header text-secondary text-center">
      修改密码
    </div>
    <div class="card-body">
      <%= render partial: 'shared/errors', locals: { demo: @user } %>
      <%= form_for(:password_alter, url: password_alter_path(current_user), method: :put ) do |f| %>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">旧密码</label>
          <div class="col-sm-10">
            <%= f.password_field :old_password, class: "form-control", autofocus: true %>
          </div>
        </div> 
        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">新密码</label>
          <div class="col-sm-10">
            <%= f.password_field :password, class: "form-control" %>
          </div>
        </div>
   
        <div class="form-group row">
          <label class="col-sm-2 col-form-label text-secondary">密码确认</label>
          <div class="col-sm-10">
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label"></label>
          <div class="col-sm-10">
            <%= f.submit "修改密码", class: "btn btn-primary btn-sm"%>
          </div> 
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/password_alters/edit.html.erb
<% provide(:title, t('alter_password')) %>
<div class="row">
  <%= render 'shared/basic_bar' %>
  <%= render 'password_edit' %>
</div>