config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout',  to: 'sessions#destroy'
  resources :users, :password_alters, :set_templates, :set_modules, only: [:edit, :update]
  resources :portraits, only: [:new, :create, :update] 
end

app/views/shared/_basic_bar.html.erb
<div class='col-md-2'>
    <div class="card">
      <div class="card-header text-secondary text-center">
        基本设置
      </div>
      <div class="card-body d-flex flex-column row-hl">
        <a href="<%= edit_user_path(current_user) %>">
          <button type="button" class="btn <%= controller_name == 'users' ? 'btn-primary' : 'btn-outline-secondary' %> btn-block">
            <i class="fa fa-user fa-fw"></i> 基本信息
          </button>
        </a>
        <a href="<%= new_portrait_path %>">
          <button type="button" class="btn <%= controller_name == 'portraits' ? 'btn-primary' : 'btn-outline-secondary' %> btn-block mt-2">
            <i class="fa fa-file-image-o fa-fw"></i> 修改头像
          </button>
        </a>
        <% unless current_user.provider %>
          <a href="<%= edit_password_alter_path(current_user) %>">
            <button type="button" class="btn <%= controller_name == 'password_alters' ? 'btn-primary' : 'btn-outline-secondary' %> btn-block mt-2">
              <i class="fa fa-key fa-fw"></i> 修改密码
            </button>
          </a>
        <% end %>
      </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% unless demo.errors.blank? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <% demo.errors.full_messages.each do |error| %>
        <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
      <% end -%>
    </ul>
  </div>
<% end -%>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-5" id="bottom">
  <p class="text-right text-secondadry">
    <small class="text-secondary">单词本, 象科技制作</small>
  </p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light mb-3" style="background:  #FFFFFF" id="top">
  <div class="container">
    <%= link_to "单词本", root_path, class: "navbar-brand text-secondary" %>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %>
            <li class="nav-item"></li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                <% if current_user.avatar.to_s.size == 0 %>
                  <img src="https://test.zhengjiajun.com/uploads/wechat/name/29/middle_avatar.png" class="rounded-circle"  width="25" height="25"/>
                <% else %>
                  <%= image_tag current_user.avatar.large.url, size: "25x25", class: "rounded-circle" %>
                <% end %>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <%= link_to "基本设置", edit_user_path(current_user), class: "dropdown-item text-secondary" %>
                <div class="dropdown-divider"></div>
                <%= link_to "退出", logout_path, method: "delete", class: "dropdown-item text-secondary" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to "登录", login_path, class: "nav-link" %></li>
          <% end -%>
        </ul>
      </div>
  </div>
</nav>